name: Generate Docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    if: github.event.pull_request.draft == false
    uses: gorgonzola-graph-db/gorgonzola-workflows/.github/workflows/gen-docs.yml@master
    secrets: inherit
