name: LDBC SNB Interactive v1 Benchmark

on:
  workflow_call:
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:
    inputs:
      scale_factor:
        description: 'Scale factor'
        required: true
        default: "1"
        type: choice
        options:
          - "1"
          - "10"
          - "30"
          - "100"

jobs:
  call-workflow:
    uses: gorgonzola-graph-db/gorgonzola-workflows/.github/workflows/interactive-v1-benchmark.yml@master
    secrets: inherit
