name: LSQB Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: gorgonzola-graph-db/gorgonzola-workflows/.github/workflows/lsqb-benchmark-workflow.yml@master
    secrets: inherit
